branch-defaults:
  main:
    environment: Newassignment-env
    repository: https://github.com/Andrew-Joyce/cloud_assignment.git
environment-defaults:
  Newassignment-env:
    branch: main
    repository: https://github.com/Andrew-Joyce/cloud_assignment.git
global:
  application_name: new_assignment
  default_ec2_keyname: null
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application

