branch-defaults:
  main:
    environment: Newassignment-env
environment-defaults:
  Newassignment-env:
    branch: null
    repository: null
global:
  application_name: new_assignment
  branch: main
  default_ec2_keyname: AndrewJoyce
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: Newassignment
  sc: git
  workspace_type: Application
