branch-defaults:
  default:
    environment: Newassignment-env
    group_suffix: null
  main:
    environment: Newassignment-env
environment-defaults:
  Assignemnt3-env:
    branch: null
    repository: null
  Newassignment-env:
    branch: null
    repository: null
  my-flask-env:
    branch: null
    repository: null
global:
  application_name: new_assignment
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.9
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
